services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    ports:
      - httpPort: 5678
        urlPath: "/"
    command: "npm run start"
    instanceType: free
    envVars:
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_RUNNERS_MODE
        value: "internal"
